spring.application.name=food-service
server.port=9091

spring.datasource.url=jdbc:mysql://localhost:3306/foodDB
spring.datasource.username=root
spring.datasource.password="{cipher}e427305cb6f480709f25f257de18ff43d130f4cbddea3756102b94e7d88ddfb8"

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configure Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/



info.app.name=Food Service
info.app.description=Configurtaion Service for managing food items
info.app.version=1.0.0

management.endpoints.web.exposure.include=*
management.info.env.enabled=true
management.info.app.enabled=true
