spring.application.name=restaurant-service
server.port=9092


spring.datasource.url=jdbc:postgresql://localhost:5432/restoDB
spring.datasource.username=user
spring.datasource.password={cipher}fc2150e7b1a0ea86a1f50eaaa670970f4574f11000cf75ac57f8012597a86a5c


# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configure Eureka Client properties
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

info.app.name=Restaurant Service
info.app.description=Service for managing restaurant 
info.app.version=1.0.0

management.endpoints.web.exposure.include=*
management.info.env.enabled=true
management.info.app.enabled=true
